### ISSUE TITLE
Issue with page rendering on ios in horizontal mode.

### ISSUE THREAD

**Issue by Master3008** [ttu-ttu/ebook-reader#170]
Horizontal mode on ios seems to be broken, it doesn’t render the whole page and scrolling is blocked when using paginated view mode. I’m using safari on ios 15.5.

**Comment by ChaseOxide** [comment]
Don't think this is fixable from our side

**Comment by Master3008** [comment]
I found the issue but I have no idea how to fix it.
Basically in the file `book-reader-paginated.svelte` there is this part of the code:

`.book-content-container {
    column-count: var(--book-content-column-count, 1);
    column-gap: 20px;
    column-fill: auto;
    height: var(--book-content-child-height, 95vh);
  }`

For some reason ios safari doesn't render the page correctly if `column-count` is set to 1. If i set it to any other value the page works correctly. I'll try to find a solution to this bug but maybe you have some ideas.

**Comment by Master3008** [comment]
I found a user on stackoverflow that has this same problem: https://stackoverflow.com/questions/71319077/columns-or-column-count-1-not-working-safari .
I think a solution would be to explicitly set `column-width` to the size of the element `book-content` when `column-count` has value 1. I do not know how to do this because I am not familiar with svelte and I'm not sure how to turn `column-width` into a varible without breaking the page on all other browsers, but I this this issue is fixable, so if you have some time to try it I would be really grateful!
