### ISSUE TITLE
[Feature Request] Additional options for sorting

### ISSUE THREAD

**Issue by MatthiasvZ** [ttu-ttu/ebook-reader#187]
This isn't a major issue or anything.
But I've wondered whether it might be possible to add additional options for sorting on the home screen.
E.g. going back to sorting only by _date added_ or maybe even _alphabetically_, so that novel series don't end up being all jumbled up the way they are right now.

![ttu](https://user-images.githubusercontent.com/66225565/191834911-109ef186-de51-444c-a520-15f57047058c.jpg)

**Comment by RawToast** [comment]
Minor comment, but I actually preferred the older "non updating" home/manager page (sorting only by date added)

Would be nice as a potential option...

**Comment by Renji-XD** [comment]
@RawToast i am not 100% what you mean but i think the idea was to let the user decide the primary sort criteria from a list (with fallback to title)

like this:
![image](https://user-images.githubusercontent.com/6409827/211339888-a2233387-6a1a-497b-b5a7-60963b37adcf.png)

i guess you could chose last updated to achieve what you want (though books added in bulk will always have the same date and therefore be sorted by the title fallback)
