### ISSUE TITLE
blank pages until next chapter if this: <span class="board_3d"> 

### ISSUE THREAD

**Issue by Whitesttax** [ttu-ttu/ebook-reader#189]
My ebook had lots of this 3d board around text, to highlight stuff like name of stores 
Once that happened, I got blank pages till next chapter begins
I had to manually edit the epub and the line I had to remove was this: `<span class="board_3d">`
Reporting it just in case. Here's a bit of another chapter I found later that has it as well, 

`<p class="board"><span class="board1">ブラジル産ボア・コンストリクター　大ニシキヘビ</span></p><p class="epubfirstparagraph2">と書いてある。</p><p class="epubfirstparagraph2">　「いいところなの？」</p><p class="epubfirstparagraph2">　ニシキヘビはもう一度尾で掲示板をつついた。</p><p class="board"><span class="board1">このヘビは動物園で生まれました</span></p><p class="epubfirstparagraph2">　`

**Comment by Renji-XD** [comment]
i think you would need to share the epub or link to one with the same problem in order for this issue to being potentially picked up.

"board_3d" simply refers to a css class for which nobody will know what exactly it is doing and why it may causes layouting issues without having a reproduceable example etc.

**Comment by Renji-XD** [comment]
Closing for now due to inactivativty - feel free to reopen in case you can share some examples/file for further investigation
