### ISSUE TITLE
stronger "hide furigana" feature

### ISSUE THREAD

**Issue by cyphar** [ttu-ttu/ebook-reader#20]
I like to use my mouse to keep track of my reading position, but if you have a book that has *a lot* of furigana (such as the Harry Potter books) this leads to furigana being un-hidden very often even if you have "hide furigana" enabled. It would be nice if you had to actually click to show the furigana, or if there was a toggleable `rt { display: none; }` button that completely abolished furigana and the bolding effect on hidden-furigana words.

**Comment by wizo06** [comment]
Doesn't sound like a hard thing to implement. I'm only concerned about the user experience. Having two buttons in the setting menu for hiding furigana doesn't seem very intuitive (one for "soft hiding" and the other for "hard hiding").

**Comment by cyphar** [comment]
What if you had to click on a word in order to unhide the furigana? Do you think a lot of people would mind the functionality change?
