### ISSUE TITLE
[Feature Request] Adding more default fonts

### ISSUE THREAD

**Issue by Lyroxide** [ttu-ttu/ebook-reader#203]
In phones and Android e-readers, it is not possible to change the font. By any chance, would you add more fonts to the reader itself?

Some suggestions: Google Font's Klee One, shoui's recommended fonts: 源暎こぶり明朝 v5, 秀英体, しっぽり明朝

**Comment by Renji-XD** [comment]
skipped 秀英体 as it is not under free license
