### ISSUE TITLE
[Feature request] Horizontal text

### ISSUE THREAD

**Issue by aiko-tanaka** [ttu-ttu/ebook-reader#22]
Any chance of a 横書き feature?

**Comment by ttu-ttu** [comment]
Currently not interested in implementing support for that, so no

**Comment by IamMeWasTaken** [comment]
Reading is already tough enough as it is so it would be great if you add a horizontal reading option. Colors are great, its easy to use, has character counting but no horizontal option really is a shame.

Thank you very much for your development.
