### ISSUE TITLE
[Request] Add releases to Github page

### ISSUE THREAD

**Issue by Cephian** [ttu-ttu/ebook-reader#23]
Some people would prefer to run ttu locally with a lightweight web server so that they don't have to depend on an internet connection to read ebooks. Building the site requires both npm and over 600mb of npm dependencies to produce a small folder which can be hosted by any standard web server.

I am personally interested in creating a wrapper script with the extremely light http server [darkhttpd](https://github.com/emikulic/darkhttpd) to launch ttu lightweight and locally, and putting this script in user package repositories like the [AUR](https://aur.archlinux.org/). Adding github releases would help greatly as they can be fetched and used quickly, programmatically, and without npm.

**Comment by ttu-ttu** [comment]
Done, let me know if you need more from the release
