### ISSUE TITLE
Trying to import a book in english results in "s.package is undefined" error

### ISSUE THREAD

**Issue by kuator** [ttu-ttu/ebook-reader#258]
![Screenshot from 2023-08-16 21-58-32](https://github.com/ttu-ttu/ebook-reader/assets/25168308/6804a245-dabd-4191-8399-506c1ba21f31)

**Comment by kuator** [comment]
[the_sky_crawlers.zip](https://github.com/ttu-ttu/ebook-reader/files/12361300/the_sky_crawlers.zip)

**Comment by Renji-XD** [comment]
ty for sharing a test file - it should be fixed on the current site for at least this file. FYI - I removed your comment with the file
