### ISSUE TITLE
Continuous Reading without Loading between chapters

### ISSUE THREAD

**Issue by kanjieater** [ttu-ttu/ebook-reader#279]
I noticed that for large books on lower-spec devices the loading between chapters can take quite a bit of time. After reading a chapter you are greeted with a loading screen spinner. 

I'm wondering if there's a way to load the next chapter or two pre-emptively while the user is reading the current chapter. Since the app is pretty much idle when the user is reading it seems like this would make sense to happen in the background.

**Comment by Renji-XD** [comment]
hi,

that would effectively require to (pre) render multiple sections (the actual data is actually already loaded).
Technically possible but with the way of how the pagination mode was implemented probably not very straightforward / very hard to do... 

tbh performance is not the focus/a strength of the reader and at least i do not plan to touch this area.. therefore i close it as unplanned for the time being
