### ISSUE TITLE
Some books contains spacing that breaks yomichan's scanning

### ISSUE THREAD

**Issue by archiif** [ttu-ttu/ebook-reader#28]
I found that some books have weird spacing in them when there is a furigana which breaks yomichan's scanning:

![image](https://user-images.githubusercontent.com/60074051/142480429-24b6f36b-8eda-4604-9ca4-b43d9fe4bbe3.png)

Can the reader strip spaces like these so that yomichan scanning would work? If there is a way to remove spaces like these from the file itself, that would also be great.

**Comment by ttu-ttu** [comment]
I would consider this out of scope of the reader, but you can fix this on yomichan instead.

1. Go to Yomichan's settings page
2. Turn on Advanced
3. Look "Configure custom text replacement patterns" under Translation
4. Add a new pattern "\s" and replace it with nothing

![image](https://user-images.githubusercontent.com/83872826/142517570-68dd921e-39de-4379-a04c-3c5f913d08e9.png)
![image](https://user-images.githubusercontent.com/83872826/142517591-f9c20851-ad73-4b4c-aa71-5129f04db1d5.png)

**Comment by archiif** [comment]
Thanks, that's good enough for me
