### ISSUE TITLE
Some chapters not being counted?

### ISSUE THREAD

**Issue by Sentoss** [ttu-ttu/ebook-reader#284]
Thank you for the reader, I like using it.

I just had a small problem with it: for some books (I´ll insert an example) it show some chapters to be a 0? For some reason, doesn't count their pages, even though it displays them correctly. 

It doesn't seem to be an issue with Korean, since I tried a different book. So, I wonder why.
![image](https://github.com/ttu-ttu/ebook-reader/assets/34657765/d80ac896-a960-4731-85f3-9a43bd7edf6f)
![image](https://github.com/ttu-ttu/ebook-reader/assets/34657765/5196a96a-5c0e-47a2-9300-f837f6bac5f8)
(Both images are from the same book).

I look forward to this being fixed!

**Comment by Renji-XD** [comment]
hi,

this is in fact an "Issue" with Korean.

The reader was created with Japanese Learners / Language in mind. This includes also the character counter which will ignore everything except of japanese and some general latin characters (e. g. numbers). 
In your case therefore 99% of content is be treated as 0.

That being said - feel free to use the site as much as it useable for you but for the time being it is probably not planned to make the reader language agnostic (i will probably add a note to the readme too to make it clearer)

**Comment by Sentoss** [comment]
hmmm..., ok, np. Thank you.
