### ISSUE TITLE
Statistics side panel in book view displays incorrect reading goal data

### ISSUE THREAD

**Issue by S9B52D6** [ttu-ttu/ebook-reader#287]
I have been able to reproduce this a second time. Running Firefox 120.0.1 / macOS Monterey 12.6.2. The bug does not occur when you initially start a weekly reading goal, only after the reading goal has ended for the first time. It appears there is a day at the start/end of a cycle that is not being counted correctly.

![Screenshot 2023-12-11 at 23-26-13 ッツ Ebook Reader](https://github.com/ttu-ttu/ebook-reader/assets/11012289/fa64b67f-46fa-4048-ad9f-aa7d1b2d45a5)
[2023-12-11 at 23-26-13]
(Initial reading goal was started on the 6th, side panel shows it being started on the 5th. Remaining reading time value displays negative values. The main statistics page displays the date range for the reading period being from December 06-11)

![Screenshot 2023-12-12 at 10-50-00 ッツ Ebook Reader](https://github.com/ttu-ttu/ebook-reader/assets/11012289/72700de6-f53f-49c2-b92b-b8625ecf0739)
[2023-12-12 at 10-50-00]
(After the first day of the next reading goal time, as displayed in the statistics page, is hit, the side panel corrects itself. However, the end date for the goal is undercounted by one day. The main statistics page displays the date range for the reading period being from December 12-18.)

![Screenshot 2023-12-19 at 00-01-41 ッツ Ebook Reader](https://github.com/ttu-ttu/ebook-reader/assets/11012289/172085c7-d729-4e10-9feb-c585fe19f6a6)
[2023-12-19 at 00-01-41]
(The remaining time value once again turns negative as it passes the end date shown in the side panel.)

![Screenshot 2023-12-19 at 08-40-09 ッツ Ebook Reader](https://github.com/ttu-ttu/ebook-reader/assets/11012289/413b6ca5-b018-4528-b4f2-7ac497fb0bcc)
[2023-12-19 at 08-40-09]
(Once again, the side panel corrects itself after the end date shown in the main statistics page is passed. However, the end date for the goal in the side panel is again undercounted by one day. The main statistics page displays the date range for this reading period being from December 19-25. Additionally, even though the reading goal should have started ~9 hours ago, it's displaying that 29 hours have already passed in the current reading goal, assuming 168 hours per 7 days.)

thanks for all the improvements lately btw :)
really just a minor issue I wanted to bring to your attention if you weren't aware.

**Comment by Renji-XD** [comment]
hi,

thank you for the details - though i can't really reproduce it on my end it seems. Could you share the following:
- Go to the manager, click on the bug icon in the header and attach the json file
- Enter following snippet into the developer console (F12) "console.log(Intl.DateTimeFormat().resolvedOptions().timeZone,navigator.languages)" (without quotes) and share the result

My current assumption is that it is related to your timezone and/or browser locales which may are different between the both of us.. hopefully that your update will bring me an idea how to start fixing it ;)

**Comment by S9B52D6** [comment]
Of course, apologies for missing the debug log before. Attached it. I did update the reading goal today, so that section is changed versus what I had in the screenshots.
[log.json](https://github.com/ttu-ttu/ebook-reader/files/13718203/log.json)

Also, the output for the console command is: `America/New_York Array [ "en-US", "en" ]`.
thanks!

**Comment by Renji-XD** [comment]
@S9B52D6 hope that was the root cause - let me know in case not

**Comment by S9B52D6** [comment]
@Renji-XD Yes, that seems to have fixed it for me. Technically, I see 132 hours left for my remaining time instead of what I believe should be 128 hours for my goal ending on the 25th. That's not such a big deal though, I assume I'll see it switch over around 4:00AM on the 26th then.
Thank you!

**Comment by Renji-XD** [comment]
@S9B52D6 if i got your comment right then yea its correct (though i admit it can be confusing). While the ui shows 25/12 it effectively goes until 26/12 4AM based on your starting hours.. so for the reader it will be 25/12 (though in reality it is the 26/12) as long as 4 am is not reached.

This means
4PM 20 Dec + 5 days = 120h => 4PM 25DEC + 8h until midnight + 4h offset from start hours = 132h
