### ISSUE TITLE
Trouble when running docker compose

### ISSUE THREAD

**Issue by DigitalLurker** [ttu-ttu/ebook-reader#292]
Hello, I tried cloning the repo and running `sudo docker compose up` within the ebook-reader directory but error shows up on the `RUN pnpm build` step.

Running this on raspberry pi 4 although just started out so I might have missed something 

![image](https://github.com/ttu-ttu/ebook-reader/assets/126880206/9a3e20e0-f34d-4d37-ad77-8ec50cba6f94)

Here are some of the error lines:

![image](https://github.com/ttu-ttu/ebook-reader/assets/126880206/502b8457-e65f-486a-9a1e-6e74cc48face)
![image](https://github.com/ttu-ttu/ebook-reader/assets/126880206/561365ee-75ba-429d-9c22-ada935c91d0c)
![image](https://github.com/ttu-ttu/ebook-reader/assets/126880206/aa559448-296e-4f5b-ace5-49e58c7061ab)

Here is the full error message after running the command
[error_text.txt](https://github.com/ttu-ttu/ebook-reader/files/13787839/error_text.txt)

It however runs all right when I tried to manually run `pnpm build` on the terminal

**Comment by Renji-XD** [comment]
Probably an issue with an outdated node version - at least it runs on my side after the update. Download again / pull changes and let me know if you still facing the same issue with the updated docker file

**Comment by DigitalLurker** [comment]
Thanks a lot! it's fixed and running
