### ISSUE TITLE
[Feature Request] Add More Statistics

### ISSUE THREAD

**Issue by Neilord** [ttu-ttu/ebook-reader#299]
Hi! I believe that the current goals statistic is awesome! it can be a great motivation to keep the streak. In addition, it would be very helpful to see some more, examples I would like to:
- Reading speed graph - average reading speed over days
- Number of lookups with Yomichan - number of lookups speed over days (is it possible?)
- Books difficulty - average difficulty (to be calculated) of reading books over days (is it possible?)
(to calculate the book's difficulty and other stats services with API like [voyant-tools.org](https://voyant-tools.org/) can be used.)

**Comment by Renji-XD** [comment]
Hi,

ty for your suggestions.

1) Will be added by #270 which should contain graphs for the configured date range and existing data like characters,time and speed

2) Probably not possible to do it reliable. Only thing the reader could hook into would be highlighted words but this would generate a lot of noise with other functionality like selection to bookmark (and for sure if #21 will ever land) and also not have access of dictionary forms etc. Better to ask the yomitan team directly to integrate it inside the extension

3) Don't think there is any service available which is not just a simple short unit tokenizer / free for the amount of data required for complete epubs. While it would maybe be possible to add an scoring to books i am not really convinced that it makes sense as part of the statistics. Most people will read the same book for a longer period of time and the number will not change.. also the score would be kind of arbitrary.. without any connection to user knowledge (which is not planned to be added in the scope of this project for the time being) / known words i think the benefit is probably low. Therefore i see it as not planned right now

As only 1 as duplicate remains i will close this issue while keeping a general scoring for 3 in mind for the (not defined) future
