### ISSUE TITLE
Excessive linebreaks

### ISSUE THREAD

**Issue by orth0dox** [ttu-ttu/ebook-reader#300]
After importing text from txt file in noticed that instead in addition to preserving original linebreaks, ttsu reader introduces its own at every dot 。 quote 」brace ）and who knows what else characters. I don't see any option that regulates this behavior.
How can i force ttsu reader to stick to original linebreaks?

**Comment by Renji-XD** [comment]
Hi,

your observation is correct. Reason being the way of how the character counter works - its only updated across separate text nodes. If there wouldn't be a split there could be the risk of none or only few updates in case the file would be e. g. one long flowing text.

That said i deployed a change which should allow to keep lines below 350 characters and only apply this split in case no line break was found until this limit. 

Refresh your tab, reupload the file to update the content and let me know if that looks better in your case

**Comment by orth0dox** [comment]
Thx, it looks good now. I'm not sure how would it look on actually long paragraphs, but ones i had problem with now look like they should.

**Comment by Renji-XD** [comment]
sounds good - closing as completed
