### ISSUE TITLE
Auto add books from local folder (enhancement)

### ISSUE THREAD

**Issue by ONEsuzuki** [ttu-ttu/ebook-reader#303]
As I don't store my books in the cloud and since bookmark/read pages isn't written back to the book data on the cloud anyways, right? S wouldn't it be easier to have it auto add from local folder? I haven't seen it listed anywhere on the page I'm currently reading on android through https://github.com/lrorpilla/jidoujisho ッツ eBook Reader. 
I really like the reader design the ability to hide furigana and words with it stay highlighted grey showing that furigana has been hidden on those words is cool, just thought it would be a cool addition, unless it's already an option? Look forward to hearing from you.

**Comment by Renji-XD** [comment]
hi,

regardind your first question: if you would use e. g. gdrive you could export bookmarks/statistics either manually or automatically depending on your configuration.

For your request - not 100% if i get it right but i read it as two options

1) You ask for auto importing all supported files via a folder. This one is kind of already exists for desktop either by clicking on import folder or by dragging & dropping a folder into the reader. For mobile unfortunately no web apis/functionality exists to support this - as website nothing the reader site can do about

2) You ask for the ability of  adding folders to monitor and automatically pick up files. Simliar to the previous one - there are no web apis existing for all major browsers which would really give the required functionality (not even on desktop). Again - nothing the reader can do about as a website

Therefore unfortunately nothing which can be added the current time - so closing this issue

**Comment by ONEsuzuki** [comment]
Thanks for informative answer, have a nice day.
