### ISSUE TITLE
Cmd-f doesn't work while in a book on Mac (chrome).

### ISSUE THREAD

**Issue by Awesome-fire** [ttu-ttu/ebook-reader#306]
I have to press cmd-f on the main page and then enter the book. It worked in previous versions and on ttu-ebook.web.app.

**Comment by Renji-XD** [comment]
Hi, ty for reporting.

I deployed a change which probably addresses this - as i don't own a mac to verify it please reload the page/browser and let me know if you can use the keybind on the reader page now.

**Comment by Awesome-fire** [comment]
it works now, thank you
