### ISSUE TITLE
[Issue] Whole chapter hidden by "display:none;"

### ISSUE THREAD

**Issue by NylonNeko** [ttu-ttu/ebook-reader#313]
Loving ttsu so far, but I am running into an issue where a whole chapter is hidden by "display:none;". I tried on different browsers on different devices, still no luck. Problem is I plan to read in jidoujisho on Android where I no options to configure user styles. Any help would be appreciated.

Here are some screenshots. If you need more information feel free to tell me, I will provide whatever details I can. You can see that after the table of content, the chapter "エピローグ” is hidden. Only the image (which is part of the epilog chapter) remains.
![Screenshot_c110](https://github.com/ttu-ttu/ebook-reader/assets/37959867/05b31df7-3120-420f-a12b-aff41f51dfe6)
![Screenshot_c114](https://github.com/ttu-ttu/ebook-reader/assets/37959867/f2f78c90-6e6f-4242-a122-aa533b78de0c)
![Screenshot_c436](https://github.com/ttu-ttu/ebook-reader/assets/37959867/d95efa49-93d2-43c5-999d-f6818537ca89)

**Comment by Renji-XD** [comment]
Hello,

the reader is not setting any styles like that on its own on book content - especially not with inline styles. So it probably has to come from the book itself. 

Therefore i would suggest to unzip the epub with something like 7zip, going into the html files, remove those display:none and zip it back (renaming the extension to epub). Then reload the file in the file and it should be visible. Maybe there is also an more automated way with replace functionality of calibre but for that i have too less knowledge to share.

Let me know if that helped and if i can close this issue

**Comment by NylonNeko** [comment]
Hello again, and sorry for the late reply. Such a fast answer as well, thank you for your help. It does indeed not happen in other epubs I have, but I thought it was weird since I was able to browser through the epilogue and the beginning of the first chapter the first time I opened the app.

I will try removing the styles with Calibre, and get back here if that's what it was!

**Comment by NylonNeko** [comment]
Hi, I could successfully globally replace all display:none (there were only 4 in the whole book) with Calibre. Tested and now displays correctly in ttsu! Thought this was a problem with ttsu since it showed the pages in other apps (including Calibre) but didn´t check the styles. So thanks for the help! I close this issue as it is now solved.
