### ISSUE TITLE
Don't blur text on idling or double-clicking

### ISSUE THREAD

**Issue by ReimeiSky** [ttu-ttu/ebook-reader#318]
After about a minute of doing nothing, ttu blurs the screen's text. For slow readers like me, this is rather annoying; I'd like to be able to just read the text at my own pace, without having to touch anything. I can understand if it's intended to hide the text from others; in that case, adding a setting allowing you to change the time limit or disable it would be good.

A much bigger issue I have is blurring on double-click. Aside from being entirely counter to my unconscious habit of selecting text,
![xkcd demonstration of the highlighting problem](https://imgs.xkcd.com/comics/hilighting.png)
it's very annoying when I want to purposefully select a part of a line to focus my thinking on. I would rather replace this with a toggle button, possibly in the top bar.

**Comment by Renji-XD** [comment]
Hi,

the reader does not blur any text in any form. My guess is you are using exstatic in parallel which is exactly doing what you have described.

Therefore i can only forward you to their repository as this is not caused by out of the box functionality

**Comment by ReimeiSky** [comment]
Sorry about that. You're right, I had Exstatic installed. I had no idea Exstatic touched ttu in any way. I assumed it was strictly a VN tool.
