### ISSUE TITLE
Furigana rendering issue

### ISSUE THREAD

**Issue by rmanne** [ttu-ttu/ebook-reader#321]
|#|ttu ebook reader|Apple books|Calibre|XML|
|-|-|-|-|-|
|1|![Screenshot 2024-04-10 at 11 19 49](https://github.com/ttu-ttu/ebook-reader/assets/1724749/6da5e604-1eb2-4ad5-9f8b-d956d53bd3e9)|![Screenshot 2024-04-10 at 11 21 09](https://github.com/ttu-ttu/ebook-reader/assets/1724749/927d0ae4-88dc-43d1-a769-29c06aed0312)|![Screenshot 2024-04-10 at 11 29 09](https://github.com/ttu-ttu/ebook-reader/assets/1724749/a2fea1d5-2193-4d18-a4c4-59271fe3f0ab)|`<p class="indent-1em">...バイメーンで<ruby><a id="GBS.0014.02"/>丁寧<rt>ていねい</rt></ruby>に<ruby>掻<rt>か</rt></ruby>き回しているのは...</p>`|
|2|![Screenshot 2024-04-10 at 11 19 58](https://github.com/ttu-ttu/ebook-reader/assets/1724749/b8fcd43a-d874-4879-8f7a-5eca1f5a4382)|![Screenshot 2024-04-10 at 11 21 00](https://github.com/ttu-ttu/ebook-reader/assets/1724749/c9922217-2e67-4161-80dd-23b08ae3dbed)|![Screenshot 2024-04-10 at 11 29 19](https://github.com/ttu-ttu/ebook-reader/assets/1724749/53f770ff-837e-4b1a-a973-bb9699711960)|`<p class="indent-1em">ゆっくりと<ruby>溜息<rt><a id="GBS.0014.03"/>ためいき</rt></ruby>を<ruby>吐<rt>つ</rt></ruby>いた。</p>`|

This isn't common, I've read >7 books with this website already and haven't run into this before, but example 2 is especially confusing since the text isn't treated as furigana at all as is instead inlined into the rest of the text.

EDIT: Added the corresponding XML. My guess is ttu ebook reader isn't able to handle the seemingly random <a ... /> tags.

**Comment by Renji-XD** [comment]
Hi,

your assumption is correct. I was able to find out the book title based on your examples and it contains invalid html (the mentioned self closing anchor tags) - the reader uses the dom parser api which enforces valid html and "auto fixex" broken syntax which is in this case is probably worse ; )

Its probably an edge case and higher risk of regression for normal cases trying to manually fix broken html.. which is anyways probably not something i would like to do.

For your case i would recommend to reconvert the book in calibre and using a regex expression in "Search&replace@ to replace those faulty elements. This one seemed to work fine for me:

![image](https://github.com/ttu-ttu/ebook-reader/assets/6409827/9204f7cd-2a5c-4fe7-a906-9e106630cafe)

![image](https://github.com/ttu-ttu/ebook-reader/assets/6409827/56ecebfb-ceea-4393-9ffd-bf0f609d0ba8)

Therefore i will close this issue as won't fix - ty for your understanding ; )

**Comment by rmanne** [comment]
Makes sense, this is what I used:
```
unzip ...
sed -i 's#<a id="GBS.[0-9]*.[0-9]*"/>##g' **/*.xhtml
zip ../test.epub item/**/* META-INF/**/* mimetype
```

I imagine Calibre is doing basically the same thing with that replacement.
