### ISSUE TITLE
Google constantly asks me to sign in

### ISSUE THREAD

**Issue by SwayStar123** [ttu-ttu/ebook-reader#322]
If i use google as the storage source it will ask me constantly to sign in everytime i open up ttsu, everytime i save progress/bookmark, etc. Would be nice if the number of times im asked to login could be reduced

**Comment by Renji-XD** [comment]
hi,

this is kind of expected as the website has no server part to safely distribute a client secret / store credentials and therefore needs to reauthenticate on session timeouts or tab refreshes.

Feel free to decide if one of those options is suitable for you: [Options](https://github.com/ttu-ttu/ebook-reader?tab=readme-ov-file#security-considerations)
Paired with an own (free) set of Api Credentials (id+secret) for GDrive ([doc](https://github.com/ttu-ttu/ebook-reader?tab=readme-ov-file#storage-sources)) you can create your own Storage Source Item and reduce the amount up to completlety disable any subsequent logins based on your own risk aversion
