### ISSUE TITLE
Some statistics stop working and appear blurred

### ISSUE THREAD

**Issue by jumpluff** [ttu-ttu/ebook-reader#324]
Hi,
Thanks so much for making ttu reader! I use it everyday.
In the statistics tracker, statistics have become blurred and unreadable. Data still appears in the history database. It initially happened to Reading Time, although Reading Speed is also now not working. The problem persists between different books. Neither pausing the session nor restarting my browser fixes it, although, when I switch browser, I do not have the same problem. My other statistics are working (like the heatmap). I don't know how to replicate this right now, sorry, so this might be a useless issue.
[log (2).json](https://github.com/ttu-ttu/ebook-reader/files/15046636/log.2.json) 
![image](https://github.com/ttu-ttu/ebook-reader/assets/424515/e0839079-ceb0-42d4-8385-82d0f537019b)

Thank you for reading!

**Comment by Renji-XD** [comment]
Hi,

this is actually a feature for people who wants to track data but not see it immediately

![image](https://github.com/ttu-ttu/ebook-reader/assets/6409827/0b2abff9-6bb4-461f-be8b-f9b932cd2f05)

So just click on "Reading Speed" or "Reading Time" and it should be visible again.

Will therefore close this issue but feel free to comment again if sth is still unclear

**Comment by jumpluff** [comment]
Ah, sorry, when I click on it, nothing happens whatsoever, I did try that and should have mentioned it. When I inspect the element, I can see the numbers, so they're definitely there! Thanks.

**Comment by Renji-XD** [comment]
just to be sure - i mean not clicking on the blurred text but the actual text label like  besides it. so the red framed part (should also have a pointer cursor instead of text one)

![image](https://github.com/ttu-ttu/ebook-reader/assets/6409827/29b22938-00f8-438c-bbee-def6a8e792bb)

**Comment by jumpluff** [comment]
Oh wow, thank you! I'm so sorry I kept misunderstanding like that lol. It's amazing how many versatile features ttu has. Thank you so much for holding my hand, it works now :)
