### ISSUE TITLE
Freezing when using continuous, only full furigana books?

### ISSUE THREAD

**Issue by ConorG1247** [ttu-ttu/ebook-reader#325]
When trying to read certain books (currently ぜんぶ、藍色だった。and 泣きたい私は猫をかぶる (角川つばさ文庫)) using continuous pages my browser (opera, although I tested on chrome as well and it has the same issue) starts to run slow, freeze and then becomes unresponsive. This is only an issue with certain epubs and using paginated fixes the issue, but I've been reading using continuous with other books so it would be nice to continue with this.

After removing the furigana from the epub using a separate script it fixed the issue with 泣きたい私は猫をかぶる. 
It seems to only be an issue with full furigana books, even with furigana hidden in the reader settings it still causes a browser crashes.

Thanks.

**Comment by Renji-XD** [comment]
Hi,

that is more or less the reason why paginated exists - hidden furigana does not remove the element from the dom and also just hides them insteaed of taking them out of the document flow - therefore as you mentioned a book with a lot of those elements will perform worse.

I added one additional option which at least takes them out of the document flow which you can try out - but i don't expect a major difference. There is currently no plan to work on any direct changes of the the reader modes therefore i closed this issues with respective pr for the time being
