### ISSUE TITLE
Custom font dialog not adding font to the ebook reader

### ISSUE THREAD

**Issue by olstern01** [ttu-ttu/ebook-reader#334]
Hello. Thank you for the hard work.

I have a problem. I tried to add a font through the custom font dialog on Font Family (tried both Group 1 and Group 2), clicked the "Choose File (and click Save)", chose the desired font, but then after the browser's dialog box closes the font wasn't added to the ebook reader (when I hovered my cursor to the save logo, the cursor changes into the no symbol). I tried several times, with different fonts, but still wasn't able to add any custom fonts. 

Why does this happen? I'm using Firefox 126.0.1 (64-bit) on Windows 11 Pro. Help would be appreciated.

**Comment by Renji-XD** [comment]
hi,

have you entered a value for the font name (which is the one you have to use in the font family field afterwards)? The cursor you describes means either no file selected or no name value given (i admit the ui is not that clear here)

You know the selection should have worked when there is the respective entry under "Stored" afterwards - closing the popup effectively resets the name and previously choosen file if not saved

**Comment by olstern01** [comment]
Ah you're right! After I write the font name, I can add the font. It worked. Maybe you can add a warning below the Font Name bar in small red font, that says "you must enter a font name", so it would be clearer for users who finds the feature for the first time. 

Thank you very much for the help! I'll close this issue.
