### ISSUE TITLE
Book cover thumbnail links requested from google drive are only 220px wide

### ISSUE THREAD

**Issue by 4890A** [ttu-ttu/ebook-reader#347]
After syncing a new book with google drive, subsequent thumbnail link requests for the book cover thumbnail include =s220, which looks bad on most screens. Not sure if this is the intended behavior, but it would be nice if we could recover the original cover. 
![image](https://github.com/ttu-ttu/ebook-reader/assets/16848266/1860fe1e-2e57-48ea-b038-6f5ecf2b5bb1)

**Comment by Renji-XD** [comment]
hi,

that is the link as is returned from google. As far as i know it is reacting to changes of the value though i would probably still cap it at 720p. Higher resolutions will just increase the required bandwidth for no real benefit as the manager anyways just displays it around 300-400px
