### ISSUE TITLE
Using the file's hash as ID instead of auto-increasing ID

### ISSUE THREAD

**Issue by thanhnguyen2187** [ttu-ttu/ebook-reader#351]
Hi. I noticed that on opening books, the URL is `b?id={id}`, where `{id}` is an auto-increasing ID for each uploaded book. As I use  `ebook-reader` on both my desktop and my laptop, and use Hypothes.is to annotate the reading and synchronizing, the `{id}`s might not match each other, renders Hypothes.is unusable. To give an example:

- `/b?id=1` refers to book A on my desktop
- `/b?id=1` refers to book B on my laptop

Since Hypothes.is uses URL to locate its annotations, it does not differentiate between `/b?id=1` on my desktop, and `/b?id=1` on my laptop. I think instead of having `?id=1`. I suggest we use `?id={fileHash}`, which would solve the problem (and help with cross-device bookmarking as well).

What do you think? Thanks!

**Comment by Renji-XD** [comment]
Hi,

that would require to create new stores with new names for every existing store using the id value, copying data from old stores into the new ones and change the respective references everywhere.

While i understand your case i don't see the respective data risk for others / the # of required changes etc. as really justified for what it will bring so for the time being this is not planned and i close this issue

thanks for your understanding
