### ISSUE TITLE
Recurrent problem of offine not working fot tt-ttu reader - Firefox - Debian Linux

### ISSUE THREAD

**Issue by elemn** [ttu-ttu/ebook-reader#364]
Hello,

I have a recurrent issue with ttsu reader not working offline. Generally, this works fine, however every few months, I am offline and it no longer is able to access the app with Firefox. Actually, I'm having a feeling that it might have never worked, and that I just get lucky having accessed the reader the night before in an open session. 

Is there anything I can do to make sure that ttsu gets stored locally? I have the following settings checked: 

Persistant storage: on 
Cache data: on 

Any idea what could be going wrong? Maybe a problem with Firefox?

**Comment by Renji-XD** [comment]
Hi,

while firefox has limited support for some pwa functionality it should not relate to offline. 

Obvious points are that options or extensions which are deleting/blocking site data when firefox is closed / after specific period of time should be disabled. There should also be an option under "Privacy & Security" to add Exceptions.. maybe just to be safe you could add https://reader.ttsu.app as always allow exception. Also make sure to do normal refreshes and no hard refresh / or clearing the cache when being offline - maybe also helps.

On the site itself there is probably no 100% indicator.. you could check in the developer tools under Application that there is a service worker (and that it is green) and that the manifest tab is not showing any errors but normal data/values. Under Storage / Cache Storage there should be a build:<some_numbers> entry it should contain a list of files / urls of all main site urls. If that is the case it should in theory be able to serve you offline.

When it occurs again you may can check the console of the developer tools if there is any specific error but my assumption is you will simply see a network error. 

As this sounds infrequent and is not reproduceable on my end i will close this issue as i don't see anything specific i could check / work on - but feel free to comment back in case you found anything useful / error messages
