### ISSUE TITLE
Sudden performance issues

### ISSUE THREAD

**Issue by sZale2** [ttu-ttu/ebook-reader#384]
In the last week continuous mode has been having performance issues it wasn't a week ago.
I'm using the same settings on the same book but scrolling has become unusuably slow, and then it will crash. This persists with different books and on different browsers (brave and firefox).
I'm also using G-Drive as my storage method.
I doubt it's a specs issue but if it helps:
Processor	AMD Ryzen 7 5700X 8-Core Processor                3.40 GHz
Installed RAM	32.0 GB
Windows 10
Images below show the crash on brave and the task manager stats I grabbed before it crashed.
![image](https://github.com/user-attachments/assets/11fada14-d87f-418a-b6e9-5b845d92dd7b)
![image](https://github.com/user-attachments/assets/7a388626-4297-4683-89e9-16ccde442349)
Let me know if there's further info needed.

**Comment by Renji-XD** [comment]
probably related to the major update of svelte- i deployed the old version. let me know if the issue still exists after couple of site refreshes / browser restart

**Comment by sZale2** [comment]
> probably related to the major update of svelte- i deployed the old version. let me know if the issue still exists after couple of site refreshes / browser restart

It seems back to normal now, thank you so much👍
