### ISSUE TITLE
[Feature] Book Manager

### ISSUE THREAD

**Issue by Renji-XD** [ttu-ttu/ebook-reader#4]
As a User i want to be able to see a list of all my books i loaded to the page with the Ability to easily switch between them / delete them from the local db.

- May make sense to leverage something like https://swiperjs.com/get-started which has already touch support etc. built in (not sure yet about operation controls / ui)
- Could allow different effects as Setting
- Functionality would be available via new Icon (e. g. list) and keybind (e. g. alt+l), one icon to quick delete current book
- Modal like Settings maybe the best
- When current Book gets deleted, its navigating the User to the previous Book in the List
- When all Books are deleted, its navigating to the initial Start Screen
- Multi Selection would be nice i guess but low prio

Edit just in case: Example of mentioned swiperjs i played with for a browser extension i started to work on before this repo was public => https://imgur.com/a/6Nn54JT

**Comment by wizo06** [comment]
See #2

**Comment by Renji-XD** [comment]
No issues if that will be the final statement. It just came up in a discussion on refold discord because https://github.com/lrorpilla/jidoujisho embeded the reader and someone was asking for a quick way / list to switch between books - and as far as i know there is nothing like that on mobile (except of url manipulation etc.). I think the reader gets "more and more attention" so most likely such requests will increase in the future : )

But I think at least the delete current book icon would be useful though because currently books are added on top instead of replacing the previoys one which then simply wastes storage (and is also strange if the purpose of the app is a simple one book viewer).
