### ISSUE TITLE
[Feature] Tracker Functionality

### ISSUE THREAD

**Issue by Renji-XD** [ttu-ttu/ebook-reader#6]
As an User i want to be able to track the spent Time i am reading a book.

Timer should be pauseable (and start in pause - due to initial scrolling / or user may want to adjust the position before)
There could be different Display Modes: Time Only, previous and (real) read characters + characters/h, previous and estimated time to finish (based on read characters in specific time)
Update in 10 seconds Interval should be fine (optionally when timer enters pause state)
Potential Companion Option: Auto Pause Mode (off, lax - auto pause in case tab loses focus / dialogs are opened, strict - any loss of window focus (e .g. yomichan, leaving browser etc.) will pause)

"Simple" Case:
Global Timer

Medium Case:
Timer Data per Book (stored in new Table or among existing data)

Complex Case:
Global and Book specific Data which can be e. g. toggled

For the Beginning the Timer Data could be based on the Session (as long as Page is not reloaded etc.)
But Potentially opens up the next big use case of collecting historical Data which could be displayed with nice graphs on a separate analyics route or similar

**Comment by archiif** [comment]
I actually had a hacky userscript that implements a really simple global timer, but it stopped working in the new redesign.

In v1.x the top bar is not hide-able, so I managed to stuff the timer controls into that top bar and have it looking and working just fine.

In the new redesign the top bar autohides itself, and its design is generally not very suitable for permanent display anyways (it's kind of fat and takes space, it can potentially overlap with the text if you don't adjust the max height of the text in the settings, etc.). 

So if the timer would be officially implemented, I wonder how it should look like in the new redesign.

**Comment by ttu-ttu** [comment]
Can always put it "under" the top header (so like you can see it when the hide-able top bar hides itself), following the css styles from the word counter, or just append to the word counter text itself

If we're going with the top header design, it'll need to be hide-able from the settings since there wouldn't be a way to click on it (or hide it) otherwise

Can also just go with the simple global timer since I'm lazy to come up with a real design 🤐
