### ISSUE TITLE
[Bug] Stuck on loading screen after failure to import book

### ISSUE THREAD

**Issue by wizo06** [ttu-ttu/ebook-reader#7]
When importing a book and *ttu-ebook* fails to parse it, [an alert will pop up](https://cdn.discordapp.com/attachments/571043507549110302/858149577323577394/unknown.png).

However, the problem here is that after clicking on "OK", the pop up closes but the website gets stuck on loading screen, which prevents the user from interacting with any of the buttons.

See gif [here](https://cdn.discordapp.com/attachments/538296705758658561/860246381532938261/UlyR1kwqpj.gif)

For some odd reason, this also affected the website in incognito mode.

See screenshot [here](https://cdn.discordapp.com/attachments/538296705758658561/860246773632073807/unknown.png)

**Comment by Renji-XD** [comment]
I think that would be potentially kind of automatically "fixed" by #2 => https://imgur.com/a/1NlMcHh

Currently the loading Observable is not resetted in case of an catched error which prevents the unrendering of the overlay if i am not wrong

**Comment by wizo06** [comment]
Hopefully that does fix it. This almost never happens to me, and it only happened the last time i tried to import a book.
