### ISSUE TITLE
Font does not change (???firefox-based browsers???)

### ISSUE THREAD

**Issue by Feripe-a** [ttu-ttu/ebook-reader#71]
I'm using Librewolf. I can't change the default font. I thought it was Librewolf since it's a modified version of Firefox. But I've installed Firefox and I can't change the default font using Firefox.
I've installed Chromium. I was able to change the default font. I've installed chromium-based browsers to test: Brave and Iridium. Both of them let me change fonts.

**Comment by ttu-ttu** [comment]
I've just tested on my Firefox and seem to work fine, could be some other setting affecting it
