### ISSUE TITLE
a way to link mobile and pc? or any devices in genral

### ISSUE THREAD

**Issue by baselmagdy2** [ttu-ttu/ebook-reader#73]
hello i usually like to read on diffrent devices, i may have the same book on my pc ttu but not on my phone's and even if i have it on both when i read i don't remember my progress, therefore i am asking for anyway to sync both

**Comment by jacktheripper19** [comment]
a good source of inspiration would be the sync server of koreader 
https://github.com/koreader/koreader-sync-server.git
that provides a way to sync books through login credentials. you also have the ability to self host the sync server if you want to.
The server compare the does not store the books by itself but just stores the progress of the books and sync them based on either the name of the book or the hash of the files.

**Comment by ttu-ttu** [comment]
@jacktheripper19 Looks promising, I'll look into it when I find time
