### ISSUE TITLE
Plans for self hosting instructions

### ISSUE THREAD

**Issue by jacktheripper19** [ttu-ttu/ebook-reader#74]
Hello,

are there any plans to provide instruction on building for self hosting setups like docker and such ?

Thanks

**Comment by ttu-ttu** [comment]
We can have a Dockerfile for this, but may I know why you prefer to self host?

**Comment by jacktheripper19** [comment]
It would be great to have a Dockerfile. 

I prefer self hosting to avoid relying on external services that may fail at some point or that I can't connect to at times. My internet is not stable so it goes offline from time to time, therefore I won't be able to connect to the public instance of the reader. This won't be an issue if I'm running a local instance on my LAN network or locally on my personal machine.

I really like the project and it would be great to have it deployed to other use cases such as docker.

**Comment by ttu-ttu** [comment]
Just FYI the website also runs on PWA (which will cache all the resources in your device, allowing it to run offline), so it may not be necessary
