### ISSUE TITLE
Books skip to the end often

### ISSUE THREAD

**Issue by wJosuke** [ttu-ttu/ebook-reader#75]
Using this on iPad and on the safari browser. Works well for the most part, but often skips to the end of the book. If I have the tab open, and quickly switch to another app, then return, it often reloads the book and takes me back to the start as well.

Let me know if you need more info, thanks all.

**Comment by RawToast** [comment]
I get the same issue on Safari on an iPad, iPhone, and a MacBook. Unfortunately, Safari is just slower than Firefox/Chrome and has such issues. It's a shame as Ten10 + ttu would be better than anything available on iOS. 

We'd need pagination or some limited loading for Safari to function better.

**Comment by ttu-ttu** [comment]
From what I've tested, WebKit (the rendering engine Safari uses) has poor support on vertical writing. Not really sure what I can do about it.

That said I can probably do something to improve the load time

**Comment by RawToast** [comment]
I feel whatever solution is used for #10 is likely to improve iOS/Safari performance. My iPad basically gives up if I load a longer book like かがみの孤城 and try to use [10Ten](https://github.com/shirakaba/10ten-ja-reader), but with smaller books it manages to work fine for a short period. 

I might have to take a look into that virtual scrolling issue and play around with ttu, but I can't see myself having time to do so until golden week.

**Comment by Renji-XD** [comment]
@ChaseOxide  as you implemented pagination you may want to close this issue until further reports?

**Comment by Renji-XD** [comment]
Closing for now as pagination mode was implemented last year which should help with the general loading times
